Add Brier metrics to motion forecasting evaluation module
argoai/av2-api pull request #44
Opened 2022-04-14 07:07 UTC by wqi

## PR Summary

This PR adds Brier score-based variants of ADE and FDE to the motion forecasting evaluation module.

These metrics are implemented in an identical way to their counterparts in the AV1 repo and will be used as scoring metrics in the AV2 MF challenge.

## Testing

All functions added in this PR have been unit tested.

In order to ensure this PR works as intended, it is:

* [x] unit tested.
* [ ] other or not applicable (*additional detail/rationale required*)

## Compliance with Standards

As the author, I certify that this PR conforms to the following standards:

* [x] Code changes conform to [PEP8](https://www.python.org/dev/peps/pep-0008) and docstrings conform to the Google Python [style guide](https://google.github.io/styleguide/pyguide.html?showone=Comments#38-comments-and-docstrings).
* [x] A well-written summary explains what was done and why it was done.
* [x] The PR is adequately tested and the testing details and links to external results are included.

2022-04-14 14:04 UTC, jagjeet-singh requested changes

2022-04-14 14:04 UTC, jagjeet-singh commented on src/av2/datasets/motion_forecasting/eval/metrics.py
> +
The two functions differ by just 1 line. Maybe move most of the stuff to a common function.

2022-04-14 14:04 UTC, jagjeet-singh commented on src/av2/datasets/motion_forecasting/eval/metrics.py
> +    print(fde_vector)
remove print?

2022-04-14 14:04 UTC, jagjeet-singh commented on tests/datasets/motion_forecasting/eval/test_metrics.py
> +wrong_shape_probabilities_k6: NDArrayFloat = np.ones((5,)) / 5
[nit] One unit test for out of range probs

2022-04-30 00:00 UTC, wqi reviewed
Thanks for the review @jagjeet-singh! Updated the PR to address feedback.

2022-04-30 15:38 UTC, jagjeet-singh commented on src/av2/datasets/motion_forecasting/eval/metrics.py
> +        ValueError: If normalize=False and `forecast_probabilities` contains values outside of the range [0, 1].
Can we call them `weights` in that case? It isn't evident from the function name or docstring that weights are acceptable.

2022-04-30 15:39 UTC, jagjeet-singh approved these changes

2022-05-02 07:13 UTC, merged